-- Atomic CRM complete database setup for a new Supabase project.
-- Run once in Supabase Dashboard > SQL Editor. Do not run on a database
-- that already has these tables or policies.

begin;

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    email text not null,
    administrator boolean not null,
    user_id uuid not null references auth.users(id),
    avatar jsonb,
    disabled boolean not null default false
);

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website text,
    phone_number text,
    address text,
    zipcode text,
    city text,
    "stateAbbr" text,
    sales_id bigint references public.sales(id),
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    background text,
    avatar jsonb,
    first_seen timestamptz,
    last_seen timestamptz,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint references public.companies(id) on update cascade on delete cascade,
    sales_id bigint references public.sales(id),
    linkedin_url text
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint references public.companies(id) on update cascade on delete cascade,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    archived_at timestamptz default null,
    expected_closing_date timestamptz default null,
    sales_id bigint references public.sales(id),
    "index" smallint
);

create table public."contactNotes" (
    id bigint generated by default as identity primary key,
    contact_id bigint not null references public.contacts(id) on update cascade on delete cascade,
    text text,
    date timestamptz default now(),
    sales_id bigint references public.sales(id) on update cascade on delete cascade,
    status text,
    attachments jsonb[]
);

create table public."dealNotes" (
    id bigint generated by default as identity primary key,
    deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
    type text,
    text text,
    date timestamptz default now(),
    sales_id bigint references public.sales(id),
    attachments jsonb[]
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null references public.contacts(id) on update cascade on delete cascade,
    type text,
    text text,
    due_date timestamptz not null,
    done_date timestamptz,
    sales_id bigint
);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.influencers (
    id bigint generated by default as identity primary key,
    name text not null,
    handle_instagram text,
    handle_tiktok text,
    followers_count integer,
    female_audience_pct numeric,
    niche text,
    email text,
    phone text,
    pix_key text,
    notes text,
    avatar jsonb,
    tags bigint[] not null default '{}'::bigint[],
    assigned_user_id bigint references public.sales(id) on update cascade on delete set null,
    status text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.campaigns (
    id bigint generated by default as identity primary key,
    name text not null,
    influencer_id bigint not null references public.influencers(id) on update cascade on delete cascade,
    infoproduct_name text,
    stage text not null,
    investment numeric not null default 0,
    gross_sales numeric not null default 0,
    commission numeric not null default 0,
    start_date timestamptz,
    end_date timestamptz,
    kanban_index integer not null default 0,
    assigned_user_id bigint references public.sales(id) on update cascade on delete set null,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.sales enable row level security;
alter table public.companies enable row level security;
alter table public.contacts enable row level security;
alter table public.deals enable row level security;
alter table public."contactNotes" enable row level security;
alter table public."dealNotes" enable row level security;
alter table public.tasks enable row level security;
alter table public.tags enable row level security;
alter table public.influencers enable row level security;
alter table public.campaigns enable row level security;

grant select, insert, update, delete on
    public.companies, public.contacts, public.deals,
    public."contactNotes", public."dealNotes", public.tasks, public.tags,
    public.influencers, public.campaigns
to authenticated;
grant select on public.sales to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "Companies access for authenticated users"
on public.companies for all to authenticated using (true) with check (true);
create policy "Contacts access for authenticated users"
on public.contacts for all to authenticated using (true) with check (true);
create policy "Deals access for authenticated users"
on public.deals for all to authenticated using (true) with check (true);
create policy "Contact notes access for authenticated users"
on public."contactNotes" for all to authenticated using (true) with check (true);
create policy "Deal notes access for authenticated users"
on public."dealNotes" for all to authenticated using (true) with check (true);
create policy "Tasks access for authenticated users"
on public.tasks for all to authenticated using (true) with check (true);
create policy "Tags access for authenticated users"
on public.tags for all to authenticated using (true) with check (true);
create policy "Sales readable by authenticated users"
on public.sales for select to authenticated using (true);
create policy "Influencers access for authenticated users"
on public.influencers for all to authenticated using (true) with check (true);
create policy "Campaigns access for authenticated users"
on public.campaigns for all to authenticated using (true) with check (true);

create view public.companies_summary
with (security_invoker = on)
as
select
    c.*,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts
from public.companies c
left join public.deals d on c.id = d.company_id
left join public.contacts co on c.id = co.company_id
group by c.id;

create view public.contacts_summary
with (security_invoker = on)
as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.email_jsonb,
    jsonb_path_query_array(co.email_jsonb, '$[*].email')::text as email_fts,
    co.phone_jsonb,
    jsonb_path_query_array(co.phone_jsonb, '$[*].number')::text as phone_fts,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    c.name as company_name,
    count(distinct t.id) as nb_tasks
from public.contacts co
left join public.tasks t on co.id = t.contact_id
left join public.companies c on co.company_id = c.id
group by co.id, c.name;

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    sales_count integer;
begin
    select count(id) into sales_count from public.sales;

    insert into public.sales (first_name, last_name, email, user_id, administrator)
    values (
        new.raw_user_meta_data ->> 'first_name',
        new.raw_user_meta_data ->> 'last_name',
        new.email,
        new.id,
        sales_count = 0
    );
    return new;
end;
$$;

create function public.handle_update_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    update public.sales
    set
        first_name = new.raw_user_meta_data ->> 'first_name',
        last_name = new.raw_user_meta_data ->> 'last_name',
        email = new.email
    where user_id = new.id;

    return new;
end;
$$;

create unique index uq__sales__user_id on public.sales (user_id);

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create trigger on_auth_user_updated
after update on auth.users
for each row execute procedure public.handle_update_user();

create view public.init_state
with (security_invoker = off)
as
select count(id) as is_initialized
from (
    select id from public.sales limit 1
) as initialized_sales;

grant select on public.init_state to anon, authenticated;
grant select on public.companies_summary, public.contacts_summary to authenticated;

insert into storage.buckets (id, name, public)
values ('attachments', 'attachments', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Attachments read for authenticated users" on storage.objects;
drop policy if exists "Attachments insert for authenticated users" on storage.objects;
drop policy if exists "Attachments delete for authenticated users" on storage.objects;

create policy "Attachments read for authenticated users"
on storage.objects for select to authenticated
using (bucket_id = 'attachments');
create policy "Attachments insert for authenticated users"
on storage.objects for insert to authenticated
with check (bucket_id = 'attachments');
create policy "Attachments delete for authenticated users"
on storage.objects for delete to authenticated
using (bucket_id = 'attachments');

commit;
