-- Migration for Influencer Hub Domain Tables

-- 1. Create table influencers
create table if not exists "public"."influencers" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "handle_instagram" text,
    "handle_tiktok" text,
    "followers_count" integer,
    "female_audience_pct" numeric,
    "niche" text,
    "email" text,
    "phone" text,
    "pix_key" text,
    "notes" text,
    "avatar" jsonb,
    "assigned_user_id" bigint,
    "status" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    constraint "influencers_pkey" primary key ("id"),
    constraint "influencers_assigned_user_id_fkey" foreign key ("assigned_user_id") references "public"."sales"("id") on update cascade on delete set null
);

alter table "public"."influencers" enable row level security;

-- 2. Create table campaigns
create table if not exists "public"."campaigns" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "influencer_id" bigint not null,
    "infoproduct_name" text,
    "stage" text not null,
    "investment" numeric not null default 0,
    "gross_sales" numeric not null default 0,
    "commission" numeric not null default 0,
    "start_date" timestamp with time zone,
    "end_date" timestamp with time zone,
    "kanban_index" integer not null default 0,
    "assigned_user_id" bigint,
    "notes" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    constraint "campaigns_pkey" primary key ("id"),
    constraint "campaigns_influencer_id_fkey" foreign key ("influencer_id") references "public"."influencers"("id") on update cascade on delete cascade,
    constraint "campaigns_assigned_user_id_fkey" foreign key ("assigned_user_id") references "public"."sales"("id") on update cascade on delete set null
);

alter table "public"."campaigns" enable row level security;

-- 3. Grants for authenticated users (No public / anon access)
grant select, insert, update, delete on table "public"."influencers" to "authenticated";
grant select, insert, update, delete on table "public"."campaigns" to "authenticated";
grant select, insert, update, delete on table "public"."influencers" to "service_role";
grant select, insert, update, delete on table "public"."campaigns" to "service_role";

-- 4. RLS policies for influencers (Authenticated users only)
create policy "Authenticated users can select influencers"
on "public"."influencers" for select to authenticated using (true);

create policy "Authenticated users can insert influencers"
on "public"."influencers" for insert to authenticated with check (true);

create policy "Authenticated users can update influencers"
on "public"."influencers" for update to authenticated using (true) with check (true);

create policy "Authenticated users can delete influencers"
on "public"."influencers" for delete to authenticated using (true);

-- 5. RLS policies for campaigns (Authenticated users only)
create policy "Authenticated users can select campaigns"
on "public"."campaigns" for select to authenticated using (true);

create policy "Authenticated users can insert campaigns"
on "public"."campaigns" for insert to authenticated with check (true);

create policy "Authenticated users can update campaigns"
on "public"."campaigns" for update to authenticated using (true) with check (true);

create policy "Authenticated users can delete campaigns"
on "public"."campaigns" for delete to authenticated using (true);
