create table public.social_accounts (
    id bigint generated by default as identity primary key,
    platform text not null default 'instagram'
        check (platform = 'instagram'),
    handle text not null,
    email text,
    avatar_url text,
    encrypted_password text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.social_accounts enable row level security;

revoke all on table public.social_accounts from anon, authenticated;
grant select, insert, update, delete on table public.social_accounts to service_role;
grant usage, select on sequence public.social_accounts_id_seq to service_role;
